fallback-grpc-addr: 0.0.0.0:3030

consul:
  addr: 127.0.0.1:8500

order:
  service-name: order
  server-to-run: http
  http-addr: 10.11.71.154:8282
  grpc-addr: 10.11.71.154:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 10.11.71.154:8283
  grpc-addr: 10.11.71.154:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 10.11.71.154:8284
  grpc-addr: 10.11.71.154:5004

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672

stripe-key: "${STRIPE_KEY}"