fallback-grpc-addr: 0.0.0.0:3030
order:
  service-name: order
  server-to-run: http
  http-addr: 10.11.70.185:8282
  grpc-addr: 10.11.70.185:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 10.11.70.185:8283
  grpc-addr: 10.11.70.185:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 10.11.70.185:8284
  grpc-addr: 10.11.70.185:5004

stripe-key: "${STRIPE_KEY}"